- ros_topic_name: /clock_raw
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS
  qos_profile: CLOCK

- ros_topic_name: /vision/image_raw
  gz_topic_name: /uav/downward/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
  lazy: true

- ros_topic_name: /vision/camera_info
  gz_topic_name: /uav/downward/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
  lazy: true

- ros_topic_name: /uav/gnss/fix
  gz_topic_name: /uav/gnss/fix
  ros_type_name: sensor_msgs/msg/NavSatFix
  gz_type_name: gz.msgs.NavSat
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA

- ros_topic_name: /uav/magnetometer
  gz_topic_name: /uav/magnetometer
  ros_type_name: sensor_msgs/msg/MagneticField
  gz_type_name: gz.msgs.Magnetometer
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA

- ros_topic_name: /uav/barometer
  gz_topic_name: /uav/barometer
  ros_type_name: sensor_msgs/msg/FluidPressure
  gz_type_name: gz.msgs.FluidPressure
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA

- ros_topic_name: /uav/downward_tof/scan
  gz_topic_name: /uav/downward_tof
  ros_type_name: sensor_msgs/msg/LaserScan
  gz_type_name: gz.msgs.LaserScan
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA

- ros_topic_name: /ugv/sim/cmd_vel
  gz_topic_name: /model/ground_vehicle/cmd_vel
  ros_type_name: geometry_msgs/msg/Twist
  gz_type_name: gz.msgs.Twist
  direction: ROS_TO_GZ

- ros_topic_name: /ugv/odom
  gz_topic_name: /model/ground_vehicle/odometry
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: gz.msgs.Odometry
  direction: GZ_TO_ROS

- ros_topic_name: /ugv/tf
  gz_topic_name: /model/ground_vehicle/tf
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: gz.msgs.Pose_V
  direction: GZ_TO_ROS
