<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>car_description</name>
  <version>0.1.0</version>
  <description>R680 阿克曼转向小车描述包：URDF 与 Gazebo (gz-sim) 模型</description>
  <maintainer email="yoimiya@todo.todo">yoimiya</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
