"""Pure security-policy helpers shared by runtime validation and tests."""

from __future__ import annotations

import ipaddress


_PLACEHOLDER_FRAGMENTS = (
    "change_me",
    "change-me",
    "changeme",
    "replace_with",
    "replace-with",
    "example",
    "your_token",
    "your-token",
    "password",
)

_PLAN_GATED_COMMANDS = frozenset(
    {"mission_start", "uav_goal", "ugv_goal", "ugv_teleop"}
)


def control_token_is_strong(token: str, *, minimum_length: int = 32) -> bool:
    """Return whether a control-plane bearer token meets the local baseline.

    This is deliberately a configuration guard, not an entropy estimator.
    Production tokens should be generated by a cryptographic secret manager.
    """

    if not isinstance(token, str) or len(token) < minimum_length:
        return False
    if token != token.strip() or any(character.isspace() for character in token):
        return False
    normalized = token.lower()
    if any(fragment in normalized for fragment in _PLACEHOLDER_FRAGMENTS):
        return False
    # Reject repeated/deterministic filler that happens to satisfy the length
    # check.  Random base64/hex credentials comfortably exceed this bound.
    return len(set(token)) >= 12


def trusted_client_address(
    peer_address: str, forwarded_for: str, *, trust_proxy_headers: bool
) -> str:
    """Resolve one audit/rate-limit address without trusting arbitrary peers."""

    peer = str(peer_address).strip()
    if not trust_proxy_headers or peer not in {"127.0.0.1", "::1"}:
        return peer
    candidate = str(forwarded_for).split(",", 1)[0].strip()
    try:
        return str(ipaddress.ip_address(candidate))
    except ValueError:
        return peer


def trusted_proxy_identity(
    peer_address: str, asserted_identity: str, *, trust_proxy_headers: bool
) -> str:
    """Accept an mTLS subject only from the local trusted reverse proxy."""

    if (
        not trust_proxy_headers
        or str(peer_address).strip() not in {"127.0.0.1", "::1"}
    ):
        return ""
    identity = str(asserted_identity).strip()
    if not identity or len(identity) > 256 or any(ord(char) < 32 for char in identity):
        return ""
    return identity


def production_motion_plan_allows(
    *, production_mode: bool, command: str, mission_status: object
) -> bool:
    """Gate every production motion entry on a commissioned site plan."""

    if not production_mode or command not in _PLAN_GATED_COMMANDS:
        return True
    if not isinstance(mission_status, dict):
        return False
    plan = mission_status.get("mission_plan")
    return isinstance(plan, dict) and plan.get("commissioned") is True
