FROM docker.io/library/ros:humble-ros-base-jammy

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        geographiclib-tools \
        python3-yaml \
        ros-humble-mavros \
        ros-humble-mavros-extras \
    && /opt/ros/humble/lib/mavros/install_geographiclib_datasets.sh \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/air_ground_landing
COPY src ./src
COPY ros2_ws ./ros2_ws
COPY config ./config

RUN source /opt/ros/humble/setup.bash \
    && cd /opt/air_ground_landing/ros2_ws \
    && colcon build --packages-select air_ground_landing_ros2 --merge-install

CMD ["bash"]
